// <auto-generated />
using CenterApp.Infrasturcture.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CenterApp.Infrasturcture.Migrations
{
    [DbContext(typeof(CenterDBContext))]
    [Migration("20220727134627_addlevelMatrial")]
    partial class addlevelMatrial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CenterApp.Core.Models.Level", b =>
                {
                    b.Property<int>("Level_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Level_Id"), 1L, 1);

                    b.Property<string>("Level_Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Level_Id");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("CenterApp.Core.Models.LevelMatrial", b =>
                {
                    b.Property<int>("Level_Id")
                        .HasColumnType("int");

                    b.Property<int>("Matrial_Id")
                        .HasColumnType("int");

                    b.HasKey("Level_Id", "Matrial_Id");

                    b.HasIndex("Matrial_Id");

                    b.ToTable("LevelMatrial");
                });

            modelBuilder.Entity("CenterApp.Core.Models.Matrial", b =>
                {
                    b.Property<int>("Matrial_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Matrial_Id"), 1L, 1);

                    b.Property<string>("Matrial_Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Matrial_Id");

                    b.ToTable("Matrials");
                });

            modelBuilder.Entity("CenterApp.Core.Models.Stage", b =>
                {
                    b.Property<int>("Stage_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Stage_Id"), 1L, 1);

                    b.Property<int>("Level_Id")
                        .HasColumnType("int");

                    b.Property<string>("Stage_Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Stage_Id");

                    b.HasIndex("Level_Id");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("CenterApp.Core.Models.LevelMatrial", b =>
                {
                    b.HasOne("CenterApp.Core.Models.Level", "Level")
                        .WithMany("LevelMatrial")
                        .HasForeignKey("Level_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CenterApp.Core.Models.Matrial", "Matrial")
                        .WithMany("LevelMatrial")
                        .HasForeignKey("Matrial_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("Matrial");
                });

            modelBuilder.Entity("CenterApp.Core.Models.Stage", b =>
                {
                    b.HasOne("CenterApp.Core.Models.Level", "Level")
                        .WithMany("Stages")
                        .HasForeignKey("Level_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("CenterApp.Core.Models.Level", b =>
                {
                    b.Navigation("LevelMatrial");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("CenterApp.Core.Models.Matrial", b =>
                {
                    b.Navigation("LevelMatrial");
                });
#pragma warning restore 612, 618
        }
    }
}
